# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'دنبال کردن', 'verbose_name_plural': 'دنبال کردن\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب\u200cها'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کامنت دهنده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.Media', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='caption',
            field=models.CharField(max_length=60, verbose_name='عنوان برچسب'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('who', 'whom')]),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('liker', 'media')]),
        ),
    ]
